### ISSUE TITLE
.rvmrc failed to load

### ISSUE THREAD

**Issue by ntodd** [basecamp/pow#300]
Pow: 0.4.0
RVM: 1.14.3
Shell: zsh

``` bash
# .powenv
if [ -f "$rvm_path/scripts/rvm" ] && [ -f ".rvmrc" ]; then
  source "$rvm_path/scripts/rvm"
  source ".rvmrc"
fi
```

``` bash
# .rvmrc
environment_id="ruby-1.9.2-p290@foo"
if [[ -d "${rvm_path:-$HOME/.rvm}/environments"
  && -s "${rvm_path:-$HOME/.rvm}/environments/$environment_id" ]]
then
  \. "${rvm_path:-$HOME/.rvm}/environments/$environment_id"
  [[ -s "${rvm_path:-$HOME/.rvm}/hooks/after_use" ]] &&
    \. "${rvm_path:-$HOME/.rvm}/hooks/after_use" || true
else
  # If the environment file has not yet been created, use the RVM CLI to select.
  rvm --create  "$environment_id" || {
    echo "Failed to create RVM environment '${environment_id}'."
    return 1
  }
fi
```

```
# Error

Error: '/Users/Nate/Development/PA/Client/TestApp/.rvmrc' failed to load:
'/Users/Nate/Library/Application Support/Pow/Versions/0.4.0/libexec/pow_rvm_deprecation_notice' 'testapp.dev'
source '/Users/Nate/.rvm' > /dev/null &&
source '/Users/Nate/Development/PA/Client/TestApp/.rvmrc' > /dev/null &&
env > '/var/folders/ys/4ryblg1s5jg_ggtbs15h6m8w0000gn/T/pow.50957.1340648851135.34057'
Error: '/Users/Nate/Development/PA/Client/TestApp/.rvmrc' failed to load:
'/Users/Nate/Library/Application Support/Pow/Versions/0.4.0/libexec/pow_rvm_deprecation_notice' 'testapp.dev'
source '/Users/Nate/.rvm' > /dev/null &&
source '/Users/Nate/Development/PA/Client/TestApp/.rvmrc' > /dev/null &&
env > '/var/folders/ys/4ryblg1s5jg_ggtbs15h6m8w0000gn/T/pow.50957.1340648851135.34057'
    at ChildProcess.exithandler (child_process.js:282:15)
    at ChildProcess.emit (events.js:70:17)
    at maybeExit (child_process.js:362:16)
    at Process.onexit (child_process.js:398:5)
```

Thanks,
Nate

**Comment by gotoAndBliss** [comment]
Just having a .rvmrc or .powrc or .powenv file would crash regardless. The reason being is because a `PATH` wasn't accessible. Adding this line before the .yourFile fixed it 

```
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```
