### ISSUE TITLE
Error Starting Rails App

### ISSUE THREAD

**Issue by kenips** [basecamp/pow#303]
Not quite sure what's wrong - `rails s` is fine, `rackup` is fine, but fails with pow. Any idea?

```
ArgumentError: wrong number of arguments (1 for 0)
~/.rbenv/versions/1.9.3-p194/gemsets/324/gems/test-unit-2.5.0/lib/test-unit.rb:10:in `run'
~/Code/railsapp/config.ru:4:in `block in <main>'
/usr/local/Cellar/pow/0.4.0/libexec/node_modules/nack/lib/nack/builder.rb:4:in `instance_eval'
/usr/local/Cellar/pow/0.4.0/libexec/node_modules/nack/lib/nack/builder.rb:4:in `initialize'
~/Code/railsapp/config.ru:1:in `new'
```

It's a pretty simple rails app with default config.ru.

**Comment by techsethi** [comment]
I tried *@superilk* solution. It worked for me. https://twitter.com/mildmojo/statuses/212604092567138305

I could not remove test-unit from my Gemfile (even though I am not using mini-test) as Rails console would not load up, if I remove it. Apparently in my seup, Rspec is looking for mini-test as a dependency.

**Comment by danmoore2205** [comment]
:+1: for @superbilk self.run solution.
