### ISSUE TITLE
TypeError: Object ... has no method 'split'

### ISSUE THREAD

**Issue by derencius** [basecamp/pow#32]
Hi

I'm trying to run a Rails 2.3.10 app and I get the erro below. Meanwhile I'm trying to write a failing test case, but I'm still figuring out how to use cake. 

Meanwhile, I edit the lines 257-261 on nack/lib/client.js from:

```
        for (k in rawHeaders) {
          vs = rawHeaders[k];
          v = vs.split("\n");
          this.headers[k] = v.length > 0 ? v.join("\r\n" + k + ": ") : vs;
        }
```

to

```
        for (k in rawHeaders) {
          vs = rawHeaders[k];
          this.headers[k] = vs;
        }
```

and I could run the app. 

The error is this: 

```
TypeError: Object _loja_session=BAh7BzoTdXNlci5yZXR1cm5fdG8iCy9hZG1pbjoPc2Vzc2lvbl9pZCIlNzI2OThmZmU0M2FlYmYzOGIzZGZjN2U3MDBjMzNjMTk%3D--3a112c99fb073ac3889376db7612d608af144918; path=/; HttpOnly has no method 'split'
TypeError: Object _loja_session=BAh7BzoTdXNlci5yZXR1cm5fdG8iCy9hZG1pbjoPc2Vzc2lvbl9pZCIlNzI2OThmZmU0M2FlYmYzOGIzZGZjN2U3MDBjMzNjMTk%3D--3a112c99fb073ac3889376db7612d608af144918; path=/; HttpOnly has no method 'split'
at ClientResponse._receiveData (/Users/marcus/Library/Application Support/Pow/Versions/0.2.2/node_modules/nack/lib/client.js:259:22)
at [object Object].<anonymous> (/Users/marcus/Library/Application Support/Pow/Versions/0.2.2/node_modules/nack/lib/client.js:46:33)
at [object Object].emit (events.js:64:17)
at Client.<anonymous> (/Users/marcus/Library/Application Support/Pow/Versions/0.2.2/node_modules/nack/node_modules/netstring/lib/ns.js:206:26)
at Client.emit (events.js:64:17)
at Client._onReadable (net.js:672:14)
at IOWatcher.onReadable [as callback] (net.js:177:10)
```

**Comment by mysmallidea** [comment]
Look at any headers that are being set in your app. For me, it was pagination headers, which were being set to numeric values. 

      headers['X-Page'] = @page
      headers['X-Per-Page'] = @per_page
      headers['X-Total-Pages'] = @total_count

Turning the numeric values into a string fixed this issue. 

      headers['X-Page'] = @page.to_s
      headers['X-Per-Page'] = @per_page.to_s
      headers['X-Total-Pages'] = @total_count.to_s
