### ISSUE TITLE
EOFError raised when rails controller action raises an exception

### ISSUE THREAD

**Issue by inglesp** [basecamp/pow#339]
I have a rails app, and making a request to a controller action that then raises an exception triggers an EOFError in Pow.

The full trace is:

```
/Users/peter/Library/Application Support/Pow/Versions/0.4.0/node_modules/nack/lib/nack/server.rb:97:in `read_nonblock'
/Users/peter/Library/Application Support/Pow/Versions/0.4.0/node_modules/nack/lib/nack/server.rb:97:in `block (2 levels) in start'
/Users/peter/Library/Application Support/Pow/Versions/0.4.0/node_modules/nack/lib/nack/server.rb:86:in `each'
/Users/peter/Library/Application Support/Pow/Versions/0.4.0/node_modules/nack/lib/nack/server.rb:86:in `block in start'
/Users/peter/Library/Application Support/Pow/Versions/0.4.0/node_modules/nack/lib/nack/server.rb:66:in `loop'
/Users/peter/Library/Application Support/Pow/Versions/0.4.0/node_modules/nack/lib/nack/server.rb:66:in `start'
/Users/peter/Library/Application Support/Pow/Versions/0.4.0/node_modules/nack/lib/nack/server.rb:13:in `run'
/Users/peter/Library/Application Support/Pow/Versions/0.4.0/node_modules/nack/bin/nack_worker:4:in `<main>'
```

I'm running Pow 0.4.0 on OSX 10.7.5.

**Comment by RobinDaugherty** [comment]
I finally found the cause of this: https://github.com/josh/nack/pull/42

**Comment by RobinDaugherty** [comment]
Here's a temporary patch: https://gist.github.com/RobinDaugherty/2731f20d303e6506d451384df2189210

If you update or reinstall Pow, you'll have to re-apply this patch. Hopefully https://github.com/josh/nack/pull/42 will get merged and released, and then Pow will be updated.

**Comment by kevinelliott** [comment]
First of all, thank you for hunting this down. It has been paining me for a long time now.

It looks to me that https://github.com/josh/nack is no longer supported and has been archived by https://github.com/josh which is a shame. I suppose the bigger shame is that https://github.com/basecamp/pow is built on something no longer maintained.

Also, read something that pow's 0.6.0 was the last release (or something to that effect).

This leads me to two conclusions:

1. `pow` needs to be maintained by new owners and then updated to get off of `nack` and onto something that is more modern and maintained
2. a modern replacement for `pow` needs to surface

I can only imagine that the reasons for people abandoning these projects is that there isn't enough demand and that they have moved onto other projects, frameworks, and languages. But there is most definitely a wild need here still.

Though I could be wrong.

**Comment by iloveitaly** [comment]
Looks like https://github.com/puma/puma-dev is the successor to pow. 0.6.0 was the last release: https://github.com/basecamp/pow/pull/549/files

Thanks for the patch! Helpful for not having to retool my dev server setup.

**Comment by RobinDaugherty** [comment]
Ditto puma-dev. It's missing the polish, helpful error messages, and ability to host static sites in a `public` folder, but gives me local SSL, which I need for things like iOS applications.
