### ISSUE TITLE
Error: Response was not received

### ISSUE THREAD

**Issue by skylord73** [basecamp/pow#352]
Error: Response was not received
    at Client._finishRequest (/Users/xxx/Library/Application Support/Pow/Versions/0.4.0/node_modules/nack/lib/client.js:77:27)
    at Client.<anonymous> (/Users/xxx/Library/Application Support/Pow/Versions/0.4.0/node_modules/nack/lib/client.js:38:21)
    at Client.emit (events.js:88:20)
    at Array.0 (net.js:335:10)
    at EventEmitter._tickCallback (node.js:190:38)

This error happens very often, but if I reload the same page, it start working.
My site is of course local, but the db is Remote, and I experienced the error usually in long loading time pages.
The error happens immediatly after the click (less then a second)

POW 0.4.0
Rails 3.0.15
Ruby 1.8.7
RVM 1.17.8
OSX 10.8.2

**Comment by noahgibbs** [comment]
This seems like some kind of generic error when stuff isn't running properly. Unfortunately, no clue how to get more information to debug :-(

Would be nice if there were a log or equivalent that could be dumped from pow.
