### ISSUE TITLE
TypeError: Cannot read property 'join' of null

### ISSUE THREAD

**Issue by rlarcombe** [basecamp/pow#403]
I am attempting to access my application via pow at http://myapp.dev, and I am getting the following error. Any ideas what might be going wrong?

Error starting application

Your Rack app raised an exception when Pow tried to run it.

TypeError: Cannot read property 'join' of null

TypeError: Cannot read property 'join' of null
    at ClientResponse.exports.ClientResponse.ClientResponse._receiveData (/Users/richardl/Library/Application Support/Pow/Versions/0.4.1/node_modules/nack/lib/client.js:249:21)
    at null.<anonymous> (/Users/richardl/Library/Application Support/Pow/Versions/0.4.1/node_modules/nack/lib/client.js:58:33)
    at EventEmitter.emit (events.js:95:17)
    at Client.<anonymous> (/Users/richardl/Library/Application Support/Pow/Versions/0.4.1/node_modules/nack/node_modules/netstring/ns.js:206:16)
    at Client.EventEmitter.emit (events.js:95:17)
    at Client.<anonymous> (_stream_readable.js:720:14)
    at Client.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:392:10)
    at emitReadable (_stream_readable.js:388:5)
    at readableAddChunk (_stream_readable.js:150:9)

**Comment by koenpunt** [comment]
@jayniz I had the same problem, thanks!

**Comment by nacengineer** [comment]
FWIW this is probably due to headers being set to nil. check your application.rb file or environment settings
