### ISSUE TITLE
 unknown process error

### ISSUE THREAD

**Issue by viktorsheshenya** [basecamp/pow#411]
Error: unknown process error
    at Socket.<anonymous> (/Users/Nile/Library/Application Support/Pow/Versions/0.4.1/node_modules/nack/lib/process.js:138:39)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:720:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:392:10)
    at emitReadable (_stream_readable.js:388:5)
    at readableAddChunk (_stream_readable.js:150:9)
    at Socket.Readable.push (_stream_readable.js:113:10)
    at Pipe.onread (net.js:511:21)

help

**Comment by trevorturk** [comment]
Future Googlers, please see issue #30 for more hints. I ran into this problem and left some notes over here, too: https://github.com/rails/rails/issues/18660#issuecomment-95593625 (In my case, the problem was that my symlink had the incorrect capitalization.)
