### ISSUE TITLE
Pow not detecting proper ruby version and gemset when using .ruby-version .ruby-gemset

### ISSUE THREAD

**Issue by bigtunacan** [basecamp/pow#463]
Using RVM with newer .ruby-version and .ruby-gemset files rather than the old .rvmrc

Pow gives message `Error starting application`

```
Bundler::GemNotFound: Could not find Ascii85-1.0.2 in any of the sources
~/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.3.5/lib/bundler/spec_set.rb:92:in `block in materialize'
~/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.3.5/lib/bundler/spec_set.rb:85:in `map!'
~/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.3.5/lib/bundler/spec_set.rb:85:in `materialize'
~/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.3.5/lib/bundler/definition.rb:114:in `specs'
~/.rvm/gems/ruby-1.9.3-p484@global/gems/bundler-1.3.5/lib/bundler/definition.rb:159:in `specs_for'
```

**Comment by ludwigschubert** [comment]
+1

**Comment by Manuite** [comment]
+1

**Comment by YiNdeMiiD** [comment]
+1

**Comment by jasonhutchens** [comment]
The fix to this is to create a `.powrc` file with the following contents:

```
if [ -f "$rvm_path/scripts/rvm" ] && [ -f ".ruby-version" ] && [ -f ".ruby-gemset" ]; then
  source "$rvm_path/scripts/rvm"
  rvm use `cat .ruby-version`@`cat .ruby-gemset`
fi
```

**Comment by onpaws** [comment]
@jasonhutchens thanks, that seems _so_ close to working. 
I'm manually restarting pow with `launchd` but unfortunately having no luck.
`.powrc` goes into the Rails app folder right?

Anyone know the trick trick here?

El Capitan 10.11.6/Ruby 2.3.1/RVM 1.27.0 & .ruby-version & .ruby-gemset

**Comment by jasonhutchens** [comment]
@onpaws no, `.powrc` should be in the same folder as `.ruby-version` and `.ruby-gemset`, which should be the root folder of your rails project. the `app` directory is a subdirectory of that. works for me; when I need to restart the server I do `touch log/restart.txt`, and when I need to restart the `pow` process I do `touch ~/.pow/restart.txt`

**Comment by onpaws** [comment]
Hooray, got it working!
Thanks for clarifying @jasonhutchens
(I had meant the Rails project folder, apologies for the ambiguous wording.)

**Comment by onpaws** [comment]
For future folks, in my experience just now, restarting Pow worked with
`touch tmp/restart.txt` (Passenger style)

`touch log/restart.txt` didn't seem to do anything

**Comment by jasonhutchens** [comment]
typo on my behalf, now fixed :/
