### ISSUE TITLE
closed stream (IOError)

### ISSUE THREAD

**Issue by stereodenis** [basecamp/pow#509]
```
powder log    
WARNING /Users/stereodenis/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:97:in `eof?': closed stream (IOError)
WARNING       from /Users/stereodenis/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:97:in `block (2 levels) in start'
WARNING       from /Users/stereodenis/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:96:in `each'
WARNING       from /Users/stereodenis/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:96:in `block in start'
WARNING       from /Users/stereodenis/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:76:in `loop'
WARNING       from /Users/stereodenis/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:76:in `start'
WARNING       from /Users/stereodenis/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:12:in `run'
WARNING       from /Users/stereodenis/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/bin/nack_worker:4:in `<main>'
DEBUG nack worker exited
DEBUG nack worker exited
```
https://github.com/rodreegez/powder/issues/121

UPD: I think it is connected with https://github.com/basecamp/pow/issues/507

**Comment by caesarsol** [comment]
I have the same issue, but it's just a logged warning.
It doesn't compromise the developing application.

Does it for you?

**Comment by robbieshepherd** [comment]
getting the same error here, causes a ERR_EMPTY_RESPONSE in the browser.

```[Fri Jan 15 2016 10:06:26 GMT+1100 (AEDT)] WARNING /Users/robbie/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:97:in `eof?': closed stream (IOError)
[Fri Jan 15 2016 10:06:26 GMT+1100 (AEDT)] WARNING 	from /Users/robbie/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:97:in `block (2 levels) in start'
[Fri Jan 15 2016 10:06:26 GMT+1100 (AEDT)] WARNING 	from /Users/robbie/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:96:in `each'
[Fri Jan 15 2016 10:06:26 GMT+1100 (AEDT)] WARNING 	from /Users/robbie/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:96:in `block in start'
[Fri Jan 15 2016 10:06:26 GMT+1100 (AEDT)] WARNING 	from /Users/robbie/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:76:in `loop'
[Fri Jan 15 2016 10:06:26 GMT+1100 (AEDT)] WARNING 	from /Users/robbie/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:76:in `start'
[Fri Jan 15 2016 10:06:26 GMT+1100 (AEDT)] WARNING 	from /Users/robbie/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:12:in `run'
[Fri Jan 15 2016 10:06:26 GMT+1100 (AEDT)] WARNING 	from /Users/robbie/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/bin/nack_worker:4:in `<main>'```

I'm on Ruby 2.2.2, Rails 4.2.5, Active Admin.
What I've found is that if I post from a form with an enctype: "multipart/form-data" attribute and the form doesn't have a file input, then I get this error. If I remove the enctype: "multipart/form-data" from the form tag then all works and I don't get the error. Unfortunately in active admin I have a use case where the multipart attribute has to be there at all times, regardless of whether there's a file input or not

**Comment by newdark** [comment]
I can confirm that I have the same settings as @robbieshepherd. I am running *ruby-2.2.2* and *rails 4.2.5.1*. The strange this is this error only seams to happen on some pages of the application. hard to track down but I can work around it using pow or thin. The strange part is the the rails app responds with html to render it just that the node tool does not seam to capture the data. 

```
[Tue Mar 08 2016 11:51:22 GMT-0600 (CST)] DEBUG nack worker 13285 spawned
[Tue Mar 08 2016 11:52:39 GMT-0600 (CST)] WARNING /Users/bran0899/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:82:in `select': closed stream (IOError)
[Tue Mar 08 2016 11:52:39 GMT-0600 (CST)] WARNING 	from /Users/bran0899/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:82:in `block in start'
[Tue Mar 08 2016 11:52:39 GMT-0600 (CST)] WARNING 	from /Users/bran0899/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:76:in `loop'
[Tue Mar 08 2016 11:52:39 GMT-0600 (CST)] WARNING 	from /Users/bran0899/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:76:in `start'
[Tue Mar 08 2016 11:52:39 GMT-0600 (CST)] WARNING 	from /Users/bran0899/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/lib/nack/server.rb:12:in `run'
[Tue Mar 08 2016 11:52:39 GMT-0600 (CST)] WARNING 	from /Users/bran0899/Library/Application Support/Pow/Versions/0.5.0/node_modules/nack/bin/nack_worker:4:in `<main>'
[Tue Mar 08 2016 11:52:39 GMT-0600 (CST)] DEBUG nack worker exited
```

**Comment by newdark** [comment]
Found the problem. It is rails `ActionController::Live` if you are using any live actions on your controllers it looks like it does not send the close single anymore when you go from rails 4.1 to rails 4.2. Don't know how this helps but by commenting that one line of code out of my controller everything started responding again.
