### ISSUE TITLE
Pow Installation Broken After Homebrew Install

### ISSUE THREAD

**Issue by Undistraction** [basecamp/pow#536]
Installed Pow using `brew install pow`. The install completed successfully, however running pow generates:

```
fs.js:1299
    throw error;
    ^

Error: watch /Users/me/Library/Application Support/Pow/Hosts ENOENT
    at exports._errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1297:19)
    at Object.fs.watch (fs.js:1322:11)
    at Daemon.<anonymous> (/usr/local/Cellar/pow/0.5.0/libexec/lib/daemon.js:36:35)
    at emitNone (events.js:86:13)
    at Daemon.emit (events.js:185:7)
    at pass (/usr/local/Cellar/pow/0.5.0/libexec/lib/daemon.js:95:22)
    at /usr/local/Cellar/pow/0.5.0/libexec/lib/daemon.js:116:22
    at DnsServer.<anonymous> (/usr/local/Cellar/pow/0.5.0/libexec/lib/daemon.js:83:22)
    at DnsServer.g (events.js:292:16)
```

Looking at my user directory, there is no `.pow` directory and no `~/Library/Application Support/pow` directory. So it appears neither of these are created when installing with homebrew on OSX 10.11.6

**Comment by flaviocamilo** [comment]
Did you follow the necessary steps after the installation?

pow: stable 0.5.0
Zero-config Rack server for local apps on macOS
http://pow.cx/
/usr/local/Cellar/pow/0.5.0 (691 files, 10.3M) *
  Built from source on 2016-10-14 at 08:03:14
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/pow.rb
==> Dependencies
Required: node ✔
==> Caveats
Create the required host directories:
  mkdir -p ~/Library/Application\ Support/Pow/Hosts
  ln -s ~/Library/Application\ Support/Pow/Hosts ~/.pow

Setup port 80 forwarding and launchd agents:
  sudo pow --install-system
  pow --install-local

Load launchd agents:
  sudo launchctl load -w /Library/LaunchDaemons/cx.pow.firewall.plist
  launchctl load -w ~/Library/LaunchAgents/cx.pow.powd.plist
